### ISSUE TITLE
Create and Implement layout for Tracker page

### ISSUE THREAD

**Issue by PBS-Admin** [PBS-Admin/pbs-dealer-app#10]
- [x] Determine which fields should be in quote table
- [x] Add copy option in the actions column
- [x] Create a layout for the page that matches the current styles
- [x] Ensure the layout is responsive on tablet and mobile
- [x] Test different sizes of names and see if you need to limit characters or have a max-width on columns
